[package]
name = "unifed-tff"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "tff is TensorFlow Federated for short, it's based on TensorFlow."
language = "python"


install_script = """
if { conda env list | grep 'colink-protocol-unifed-tff'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-tff
fi
conda create -n colink-protocol-unifed-tff python=3.9 -y
conda activate colink-protocol-unifed-tff
pip install .
"""

entrypoint = """
conda activate colink-protocol-unifed-tff
unifed-tff
"""
